services:

  caddy:
    image: "caddy:2-alpine"
    env_file:
      - ./domain.env
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./certs:/etc/certs
      - ./static:/static_serve

volumes:
  caddy_data:
  caddy_config:
